// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_bDKcgBIp1-D9gznxI4HyOw2Tz7MFXc',
    appId: '1:1030876898617:web:7c2f09370a14d8dfca74e8',
    messagingSenderId: '1030876898617',
    projectId: 'shrinepost-5b14f',
    authDomain: 'shrinepost-5b14f.firebaseapp.com',
    storageBucket: 'shrinepost-5b14f.firebasestorage.app',
    measurementId: 'G-EQ9ZDCDRH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4HKmiF4LExe5mPn7SRLGL1G1hwWZOjz8',
    appId: '1:1030876898617:android:fe5a9c92b5ea798dca74e8',
    messagingSenderId: '1030876898617',
    projectId: 'shrinepost-5b14f',
    storageBucket: 'shrinepost-5b14f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAayBuqS0zNDf0cFKhLGzYcFZ1-Q_9Qfg0',
    appId: '1:1030876898617:ios:440c5632c6961ba1ca74e8',
    messagingSenderId: '1030876898617',
    projectId: 'shrinepost-5b14f',
    storageBucket: 'shrinepost-5b14f.firebasestorage.app',
    iosBundleId: 'com.shrinepost.shrinePost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAayBuqS0zNDf0cFKhLGzYcFZ1-Q_9Qfg0',
    appId: '1:1030876898617:ios:440c5632c6961ba1ca74e8',
    messagingSenderId: '1030876898617',
    projectId: 'shrinepost-5b14f',
    storageBucket: 'shrinepost-5b14f.firebasestorage.app',
    iosBundleId: 'com.shrinepost.shrinePost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj_bDKcgBIp1-D9gznxI4HyOw2Tz7MFXc',
    appId: '1:1030876898617:web:e81d32543e19579fca74e8',
    messagingSenderId: '1030876898617',
    projectId: 'shrinepost-5b14f',
    authDomain: 'shrinepost-5b14f.firebaseapp.com',
    storageBucket: 'shrinepost-5b14f.firebasestorage.app',
    measurementId: 'G-TXKH0TC1P2',
  );
}
